project:
  type: website  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "Documentation for unpublished version in development: `0.1.0`"
format:
  html: 
    toc: true


website:
  title: "gedcom"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Genealogical information"
        file: "genealogy/index.qmd"
      - text: "The GEDCOM standard"
        file: technical/index.qmd
      - text: "API documentation"
        file: technical/api.qmd               

      
    right:   
      - icon: github
        href: https://github.com/neelsmith/GedCom.jl
        aria-label: GitHub

  sidebar:
    - title: "Genealogical information"
      contents: 
        - genealogy/index.qmd
        - genealogy/genealogies.qmd
        - genealogy/individuals.qmd
        - genealogy/families.qmd
        
    - title: "The GEDCOM standard"
      contents: 
        - technical/index.qmd
        - technical/datablocks.qmd             
 



